<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>online.codeisfun</groupId>
        <artifactId>maven-plugins</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <groupId>online.codeisfun.java-serializers</groupId>
    <artifactId>java-serializers</artifactId>
    <packaging>pom</packaging>
    <name>CodeIsFun :: Plugins :: Java Serializers</name>
    <modules>
        <module>java-serializer-plugin</module>
        <module>java-serializer-plugin-impl-kryo</module>
        <module>java-serializer-plugin-impl-json</module>

        <module>java-serializer-plugin-test-kryo</module>
        <module>java-serializer-plugin-test-json</module>
    </modules>
</project>