<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>online.codeisfun</groupId>
    <artifactId>maven-plugins</artifactId>
    <name>CodeIsFun :: Plugins</name>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.plugin.plugin.version>3.9.0</maven.plugin.plugin.version>
        <maven.plugin.api.version>3.9.4</maven.plugin.api.version>
        <java.parser.version>3.24.4</java.parser.version>
        <auto-service.version>1.1.0</auto-service.version>
    </properties>

    <modules>
        <module>java-serializers</module>
    </modules>
</project>