package online.codeisfun.plugins.serializers.impl.json;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Charsets;
import com.squareup.javapoet.*;
import online.codeisfun.plugins.serializers.CIFClass;
import online.codeisfun.plugins.serializers.CIFJavaSerializerGeneratorInterface;
import online.codeisfun.plugins.serializers.CIFParseException;
import online.codeisfun.plugins.serializers.CIFSerializerInterface;

import javax.lang.model.element.Modifier;
import java.nio.charset.StandardCharsets;

public class CIFJavaSerializerGeneratorJsonImplementation implements CIFJavaSerializerGeneratorInterface {

    @Override
    public void initialize(TypeSpec.Builder classBuilder, CIFClass cifClass, String newClasName) {
        TypeVariableName typeVariableName = TypeVariableName.get(cifClass.getClassName());
        ClassName serializerInterface = ClassName.get(CIFSerializerInterface.class);
        ParameterizedTypeName parameterizedInterface = ParameterizedTypeName.get(serializerInterface, typeVariableName);
        classBuilder
                .addSuperinterface(parameterizedInterface)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("This class is auto-generated by CIFSerializer.\n")
                .addField(ObjectMapper.class, "objectMapper", Modifier.PRIVATE, Modifier.FINAL)
                .addMethod(createConstructor())
                .addMethod(createSerializeMethod(cifClass))
                .addMethod(createDeserializeMethod(cifClass))
        ;
    }

    private static MethodSpec createConstructor() {
        return MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addStatement("this.objectMapper = new ObjectMapper()")
                .build();
    }

    private MethodSpec createSerializeMethod(CIFClass cifClass) {
        ClassName javaObjectClassType = ClassName.bestGuess(cifClass.getPackageName() + "." + cifClass.getClassName());
        return MethodSpec.methodBuilder("serialize")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(javaObjectClassType, "object")
                .addCode("try {\n")
                .addStatement("\treturn objectMapper.writeValueAsString(object).getBytes($T.UTF_8)", ClassName.get(StandardCharsets.class))
                .addCode("} catch (Exception e) {\n")
                .addStatement("\tthrow new $T(e)", ClassName.get(CIFParseException.class))
                .addCode("}\n")
                .returns(byte[].class)
                .build();
    }

    private MethodSpec createDeserializeMethod(CIFClass cifClass) {
        ClassName javaObjectClassType = ClassName.bestGuess(cifClass.getPackageName() + "." + cifClass.getClassName());
        ArrayTypeName byteArrayType = ArrayTypeName.of(TypeName.BYTE);
        return MethodSpec.methodBuilder("deserialize")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(byteArrayType, "bytes")
                .addCode("try {\n")
                .addStatement("\treturn objectMapper.readValue(new String(bytes,StandardCharsets.UTF_8)," + cifClass.getClassName() + ".class)")
                .addCode("} catch (Exception e) {\n")
                .addStatement("\tthrow new $T(e)", ClassName.get(CIFParseException.class))
                .addCode("}\n")
                .returns(javaObjectClassType)
                .build();
    }
}
