package online.codeisfun.plugins.serializers.impl.kryo;

import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import online.codeisfun.plugins.serializers.CIFClass;
import online.codeisfun.plugins.serializers.CIFJavaSerializerAnnotationProcessor;
import online.codeisfun.plugins.serializers.CIFJavaSerializerInterface;

import javax.lang.model.element.Modifier;

public class CIFJavaSerializerKryoImplementation implements CIFJavaSerializerInterface {
    static {
        CIFJavaSerializerAnnotationProcessor.serializerClass = CIFJavaSerializerKryoImplementation.class;
    }

    @Override
    public void initialize(TypeSpec.Builder classBuilder, CIFClass cifClass,String newClasName) {
        classBuilder
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("This class is auto-generated by CIFJavaSerializerAnnotationProcessor.\n")
                .addField(String.class, "className", Modifier.PRIVATE, Modifier.FINAL)
                .addMethod(MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addStatement("this.className = $S", newClasName)
                        .build())
                .addMethod(MethodSpec.methodBuilder("getClassName")
                        .addModifiers(Modifier.PUBLIC)
                        .returns(String.class)
                        .addStatement("return className")
                        .build());
    }
}
