package online.codeisfun.plugins.serializers.impl.kryo;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy;
import com.squareup.javapoet.*;
import online.codeisfun.plugins.serializers.CIFClass;
import online.codeisfun.plugins.serializers.CIFJavaSerializerGeneratorInterface;
import online.codeisfun.plugins.serializers.CIFSerializerInterface;
import org.objenesis.strategy.StdInstantiatorStrategy;

import javax.lang.model.element.Modifier;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

public class CIFJavaSerializerGeneratorKryoImplementation implements CIFJavaSerializerGeneratorInterface {

    @Override
    public void initialize(TypeSpec.Builder classBuilder, CIFClass cifClass, String newClasName) throws ClassNotFoundException {
        TypeVariableName typeVariableName = TypeVariableName.get(cifClass.getClassName());
        ClassName serializerInterface = ClassName.get(CIFSerializerInterface.class);
        ParameterizedTypeName parameterizedInterface = ParameterizedTypeName.get(serializerInterface, typeVariableName);

        classBuilder
                .addSuperinterface(parameterizedInterface)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("This class is auto-generated by CIFSerializer.\n")
                .addField(Kryo.class, "kryo", Modifier.PRIVATE, Modifier.FINAL)
                .addMethod(createConstructor())
                .addMethod(createSerializeMethod(cifClass))
                .addMethod(createDeserializeMethod(cifClass))
        ;
    }

    private static MethodSpec createConstructor() {
        return MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addStatement("this.kryo = new Kryo()")
                .addStatement("this.kryo.setRegistrationRequired(false)")
                .addStatement("$T stdStrategy = new StdInstantiatorStrategy()", ClassName.get(StdInstantiatorStrategy.class))
                .addStatement("$T defaultStrategy = new DefaultInstantiatorStrategy(stdStrategy)", ClassName.get(DefaultInstantiatorStrategy.class))
                .addStatement("this.kryo.setInstantiatorStrategy(defaultStrategy)")
                .build();
    }

    private MethodSpec createSerializeMethod(CIFClass cifClass) {
        ClassName javaObjectClassType = ClassName.bestGuess(cifClass.getPackageName() + "." + cifClass.getClassName());
        var parameterName = cifClass.getClassName().substring(0, 1).toLowerCase() + cifClass.getClassName().substring(1);
        return MethodSpec.methodBuilder("serialize")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(javaObjectClassType, parameterName)
                .addStatement("$T byteArrayOutputStream = new ByteArrayOutputStream()", ClassName.get(ByteArrayOutputStream.class))
                .addStatement("$T output = new Output(byteArrayOutputStream)", ClassName.get(Output.class))
                .addStatement("kryo.writeObject(output, " + parameterName + ")")
                .addStatement("output.close()")
                .addStatement("return byteArrayOutputStream.toByteArray()")
                .returns(byte[].class)
                .build();
    }

    private MethodSpec createDeserializeMethod(CIFClass cifClass) {
        ClassName javaObjectClassType = ClassName.bestGuess(cifClass.getPackageName() + "." + cifClass.getClassName());
        ArrayTypeName byteArrayType = ArrayTypeName.of(TypeName.BYTE);
        return MethodSpec.methodBuilder("deserialize")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(byteArrayType, "bytes")
                .addStatement("$T byteArrayInputStream = new ByteArrayInputStream(bytes)", ClassName.get(ByteArrayInputStream.class))
                .addStatement("$T input = new Input(byteArrayInputStream)", ClassName.get(Input.class))
                .addStatement("$T deserialized = kryo.readObject(input, " + cifClass.getClassName() + ".class)", javaObjectClassType)
                .addStatement("input.close()")
                .addStatement("return deserialized")
                .returns(javaObjectClassType)
                .build();
    }
}
